server:
  port: 8523
  servlet:
    context-path: /echarts


#HttpServletRequest 的属性是否可以覆盖 controller 中 model 的同名项
spring:
  freemarker:
    allow-request-override: false
    #HttpSession 的属性是否可以覆盖 controller 中 model 的同名项
    allow-session-override: false
    #是否开启缓存
    cache: false
    #模板文件编码
    charset: UTF-8
    #是否检查模板位置
    check-template-location: true
    #Content-Type 的值
    content-type: text/html
    #是否将 HttpServletRequest 中的属性添加到 Model 中
    expose-request-attributes: false
    #是否将 HttpSession 中的属性添加到 Model 中
    expose-session-attributes: false
    #模板文件后缀
    suffix: .ftl
    #模板文件位置
    template-loader-path: classpath:/templates/

img-url: F:\data\test\png\echarts\image/
request-url: http://127.0.0.1:6666
img-url-path: F:\data\test\png\echarts

tdt:
  server:
    url: http://127.0.0.1:6666
  img:
    width: 400
    height: 400
    path: F:\data\test\png\echarts\image\
